package errors

const (
	CodeUnauthorized             = "UNAUTHORIZED"
	CodeForbidden                = "FORBIDDEN"
	CodeNotFound                 = "NOT_FOUND"
	CodeBadRequest               = "BAD_REQUEST"
	CodeQuestionIDRequired       = "QUESTION_ID_IS_REQUIRED"
	CodeCreatedByRequired        = "CREATEDBY_IS_REQUIRED"
	CodeQuestionNotFound         = "QUESTION_NOT_FOUND"
	CodeQuestionNotFoundOrNotOwn = "QUESTION_NOT_FOUND_OR_YOU_ARE_NOT_THE_OWNER"
	CodeNoFieldsToUpdate         = "NO_FIELDS_TO_UPDATE"
	CodeQuestionAlreadyActive    = "QUESTION_IS_ALREADY_ACTIVE"
	CodeInvalidCredentials       = "INVALID_CREDENTIALS"
	CodeAccountInactive          = "ACCOUNT_IS_INACTIVE"
	CodeInvalidJWTExp            = "INVALID_JWT_EXPIRATION_DURATION"
	CodeAccessTokenGenFailed     = "FAILED_TO_GENERATE_ACCESS_TOKEN"
	CodeRefreshTokenGenFailed    = "FAILED_TO_GENERATE_REFRESH_TOKEN"
	CodeRefreshTokenRequired     = "REFRESH_TOKEN_IS_REQUIRED"
	CodeInvalidRefreshToken      = "INVALID_REFRESH_TOKEN"
	CodeInvalidTokenClaims       = "INVALID_TOKEN_CLAIMS"
	CodeUserNotFound             = "USER_NOT_FOUND"
	CodeInvalidUserClaims        = "INVALID_USER_CLAIMS"
	CodeInvalidUserID            = "INVALID_USER_ID"
	CodeInvalidUserRole          = "INVALID_USER_ROLE"
)
